[package]
name = "qtcloud-devops-cli"
version = "0.10.0-alpha.2"
edition = "2021"
description = "量潮DevOps云命令行工具"
authors = ["QuantTide <opensource@quanttide.com>"]
license = "Apache-2.0"
repository = "https://github.com/quanttide/qtcloud-devops"

[lib]
name = "qtcloud_devops_cli"
path = "src/lib.rs"
crate-type = ["cdylib", "lib"]

[[bin]]
name = "qtcloud-devops"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
gix = { version = "0.66", features = ["default", "serde"] }
git2 = "0.19"
quanttide-devops = "0.2.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
regex = "1"
uuid = { version = "1", features = ["v4"] }
jiff = "0.1"
thiserror = "2"
semver = "1"
quanttide-agent = "0.1"

pyo3 = { version = "0.23", features = ["extension-module"], optional = true }

[dev-dependencies]
tempfile = "3"

[profile.coverage]
inherits = "test"
debug = 1

[package.metadata.coverage]
rust-toolchain = "stable"
command = "cargo llvm-cov --all-features --lcov --output-path target/coverage/lcov.info"
skip-features = ["python"]

[features]
default = ["cli"]
python = ["dep:pyo3"]
cli = []

[[test]]
name = "code"
path = "tests/code.rs"

[[test]]
name = "release"
path = "tests/release.rs"

[[test]]
name = "cli"
path = "tests/cli.rs"
