name: publish-cli
on:
  workflow_run:
    workflows: [build-cli]
    types: [completed]

jobs:
  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/cli
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: install uv
        run: pip install uv
      - name: download binaries from build
        uses: actions/download-artifact@v4
        with:
          pattern: qtcloud-devops-*
          path: ${{ github.workspace }}/src/cli/binaries
          merge-multiple: true
          github-token: ${{ github.token }}
          run-id: ${{ github.event.workflow_run.id }}
      - name: download package from build
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: ${{ github.workspace }}/src/cli/dist
          github-token: ${{ github.token }}
          run-id: ${{ github.event.workflow_run.id }}
      - name: publish to PyPI
        run: uv publish
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
      - name: publish to crates.io
        run: cargo publish --token ${{ secrets.CRATES_API_TOKEN }}
