name: publish-cli
on:
  workflow_run:
    workflows: [build-cli]
    types: [completed]

jobs:
  publish-pypi:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: install uv
        working-directory: src/cli/packages/python
        run: pip install uv
      - name: download package from build
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: ${{ github.workspace }}/src/cli/packages/python/dist
          github-token: ${{ github.token }}
          run-id: ${{ github.event.workflow_run.id }}
      - name: publish to PyPI
        working-directory: src/cli/packages/python
        run: uv publish
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_API_TOKEN }}

  publish-crate:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: publish to crates.io
        working-directory: src/cli
        run: cargo publish --token ${{ secrets.CRATES_API_TOKEN }}
